name: Pruebas Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ui:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias de sistema necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb

      - name: Instalar dependencias de Node.js y ejecutar Cypress
        run: |
          npm install
          xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' npx cypress run --spec "cypress/e2e/cuenta_bancaria.cy.js"
